on:
    workflow_dispatch:
    push:
      tags:
      - '*'
  
name: Upload Release
  
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - name: Setup .NET
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '8.0.x'
    
          - name: Clone
            uses: actions/checkout@v2
    
          - name: Build
            run: dotnet publish -c Release src
    
          - name: Upload
            uses: actions/upload-artifact@v3
            with:
              path: src/Artemis.Plugins.Games.SlayTheSpire/bin/x64/Release/net7.0/publish
              name: ArtemisTheSpire-Plugin

          - name: Zip Artifact
            run: |
              cd src/Artemis.Plugins.Games.SlayTheSpire/bin/x64/Release/net7.0/publish
              ls -l .
              zip -r ${{ github.workspace }}/ArtemisTheSpire-Plugin.zip *
    
          - name: Release with Notes
            uses: softprops/action-gh-release@v1
            with:
              files: ArtemisTheSpire-Plugin.zip
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  